# Generated by Django 5.1.4 on 2024-12-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgmanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roomNumber',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='TenantProfile',
        ),
    ]
