# Generated by Django 5.1.4 on 2024-12-24 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgmanage', '0002_alter_user_roomnumber_delete_tenantprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moveInDate', models.DateField()),
                ('moveOutDate', models.DateField(blank=True, null=True)),
                ('roomNumber', models.CharField(max_length=50)),
                ('pg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pgmanage.pg')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
