# Generated by Django 5.1.4 on 2024-12-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgmanage', '0003_tenantprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantprofile',
            name='moveInDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
